const skills = [
  "/MyPortfolio/php.svg",
  "/MyPortfolio/laravel-2.svg",
  "/MyPortfolio/codeigniter.svg",
  "/MyPortfolio/mysql-3.svg",
  "/MyPortfolio/react.svg",
  "/MyPortfolio/bootstrap-5-1.svg",
  "/MyPortfolio/js.svg",
  "/MyPortfolio/html.svg",
  "/MyPortfolio/css.svg",
  "/MyPortfolio/jquery-2.svg",
  "/MyPortfolio/postman.svg",
  "/MyPortfolio/android-svgrepo-com.svg",
  "/MyPortfolio/java-svgrepo-com.svg",
  "/MyPortfolio/redux.svg",
  "/MyPortfolio/nodejs.svg",
  "/MyPortfolio/python-5.svg",
  "/MyPortfolio/git.svg",
  "/MyPortfolio/github.svg",
  "/MyPortfolio/google-ads-2.svg",
  "/MyPortfolio/shopify.svg",
  "/MyPortfolio/meta-icon.svg",
]; 

export default skills;
